development:
  client_id: <%= ENV['CLIENT_ID'] %>
  client_secret: <%= ENV['CLIENT_SECRET'] %>

test:
  client_id: CLIENT_ID
  client_secret: CLIENT_SECRET

production:
  client_id: <%= Rails.application.credentials.dig(:google, :client_id) %>
  client_secret: <%= Rails.application.credentials.dig(:google, :client_secret) %>


